In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [2]:
import numpy as np
x = np.random.randn(4, 6)
y = x
y

array([[-0.39737674,  0.61583117, -0.630188  , -1.04767903, -0.17429835,
         0.56910014],
       [-0.57453371, -0.49501979, -0.20535708,  0.25945837,  1.07152031,
        -0.08334899],
       [ 0.70000984,  1.12123721,  2.24690877, -0.42452861, -0.37781427,
         1.44820397],
       [ 0.91191049,  1.13787266, -0.6347265 ,  0.43807323, -0.0160751 ,
         1.98793071]])

In [5]:
y = torch.from_numpy(x)
y

tensor([[-0.3974,  0.6158, -0.6302, -1.0477, -0.1743,  0.5691],
        [-0.5745, -0.4950, -0.2054,  0.2595,  1.0715, -0.0833],
        [ 0.7000,  1.1212,  2.2469, -0.4245, -0.3778,  1.4482],
        [ 0.9119,  1.1379, -0.6347,  0.4381, -0.0161,  1.9879]],
       dtype=torch.float64)

In [54]:
np.add(x, 1, out=x)
x

array([[11.        ,  1.87825923,  1.26400251,  1.25774188,  1.19708124,
         1.88986279],
       [ 1.55921362,  1.91425568,  1.74037082,  1.93539341,  1.83149051,
         1.8351259 ],
       [ 1.15556411,  1.09042977,  1.74788381,  1.34455246,  1.9233555 ,
         1.30660249],
       [ 1.69248565,  1.46660078,  1.85650754,  1.17102399,  1.87938364,
         1.09816538]])

In [55]:
y

array([[11.        ,  1.87825923,  1.26400251,  1.25774188,  1.19708124,
         1.88986279],
       [ 1.55921362,  1.91425568,  1.74037082,  1.93539341,  1.83149051,
         1.8351259 ],
       [ 1.15556411,  1.09042977,  1.74788381,  1.34455246,  1.9233555 ,
         1.30660249],
       [ 1.69248565,  1.46660078,  1.85650754,  1.17102399,  1.87938364,
         1.09816538]])

In [63]:
np.maximum(0, x)

array([[10.        ,  1.11236339,  0.        ,  0.11744267,  0.22606486,
         0.        ],
       [ 0.        ,  0.46217533,  0.        ,  0.98774096,  0.        ,
         0.        ],
       [ 0.23165931,  0.        ,  2.23047909,  0.        ,  0.        ,
         0.54058861],
       [ 1.50554324,  0.54163424,  0.14517687,  0.        ,  0.        ,
         0.41554909]])

In [9]:
torch.tensor([1, 3])

tensor([1, 3])

In [10]:
torch.randn(5, 3, 10)

tensor([[[-5.6600e-01, -4.4033e-01, -1.8094e-03,  5.2637e-01, -6.9864e-01,
          -1.5922e-01,  1.9976e-01, -5.0721e-01,  3.4413e-01,  1.0499e+00],
         [ 5.6158e-01, -6.2394e-01,  2.3956e+00,  1.4199e+00,  1.9983e+00,
          -6.0683e-01,  8.1836e-01, -8.7652e-02, -6.7614e-01,  1.0098e-01],
         [ 6.4413e-01, -1.6483e-01,  1.0771e+00,  5.4996e-01, -7.5819e-01,
          -1.9089e+00, -1.0025e+00,  3.7566e-01,  7.1006e-01,  1.3471e+00]],

        [[-3.0396e-01, -2.6517e-01, -3.9588e-01, -1.5038e-01, -1.4528e+00,
          -7.4300e-01, -1.4268e+00, -7.6485e-01, -2.3237e-01,  6.4778e-03],
         [-8.5077e-01, -9.8424e-01,  1.5882e+00, -1.0230e+00, -1.2409e+00,
           1.2831e-01,  1.9666e-01, -5.5582e-01, -1.4601e+00,  7.1266e-02],
         [ 9.3744e-01, -3.1936e-01, -1.0136e-01, -5.8739e-01, -4.9803e-01,
           1.0747e-01, -9.2243e-02,  6.2425e-01, -4.9104e-01,  4.4060e-01]],

        [[ 1.0437e+00,  6.1086e-01,  8.7551e-01, -4.0370e-01, -2.4223e-02,
           3.19

In [11]:
rnn = nn.LSTM(10, 20, 2)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output, (hn, cn) = rnn(input, (h0, c0))

In [12]:
output.shape

torch.Size([5, 3, 20])