In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [56]:
import numpy as np
x = np.random.randn(4, 6)
y = x
y

array([[ 1.08376545,  1.11236339, -1.35916605,  0.11744267,  0.22606486,
        -0.49807782],
       [-0.1623238 ,  0.46217533, -2.49097479,  0.98774096, -1.09123012,
        -0.30611717],
       [ 0.23165931, -0.38199489,  2.23047909, -0.51703467, -0.32041198,
         0.54058861],
       [ 1.50554324,  0.54163424,  0.14517687, -1.43170634, -0.03600347,
         0.41554909]])

In [57]:
x[0][0] = 10;
x, y

(array([[10.        ,  1.11236339, -1.35916605,  0.11744267,  0.22606486,
         -0.49807782],
        [-0.1623238 ,  0.46217533, -2.49097479,  0.98774096, -1.09123012,
         -0.30611717],
        [ 0.23165931, -0.38199489,  2.23047909, -0.51703467, -0.32041198,
          0.54058861],
        [ 1.50554324,  0.54163424,  0.14517687, -1.43170634, -0.03600347,
          0.41554909]]),
 array([[10.        ,  1.11236339, -1.35916605,  0.11744267,  0.22606486,
         -0.49807782],
        [-0.1623238 ,  0.46217533, -2.49097479,  0.98774096, -1.09123012,
         -0.30611717],
        [ 0.23165931, -0.38199489,  2.23047909, -0.51703467, -0.32041198,
          0.54058861],
        [ 1.50554324,  0.54163424,  0.14517687, -1.43170634, -0.03600347,
          0.41554909]]))

In [54]:
np.add(x, 1, out=x)
x

array([[11.        ,  1.87825923,  1.26400251,  1.25774188,  1.19708124,
         1.88986279],
       [ 1.55921362,  1.91425568,  1.74037082,  1.93539341,  1.83149051,
         1.8351259 ],
       [ 1.15556411,  1.09042977,  1.74788381,  1.34455246,  1.9233555 ,
         1.30660249],
       [ 1.69248565,  1.46660078,  1.85650754,  1.17102399,  1.87938364,
         1.09816538]])

In [55]:
y

array([[11.        ,  1.87825923,  1.26400251,  1.25774188,  1.19708124,
         1.88986279],
       [ 1.55921362,  1.91425568,  1.74037082,  1.93539341,  1.83149051,
         1.8351259 ],
       [ 1.15556411,  1.09042977,  1.74788381,  1.34455246,  1.9233555 ,
         1.30660249],
       [ 1.69248565,  1.46660078,  1.85650754,  1.17102399,  1.87938364,
         1.09816538]])

In [63]:
np.maximum(0, x)

array([[10.        ,  1.11236339,  0.        ,  0.11744267,  0.22606486,
         0.        ],
       [ 0.        ,  0.46217533,  0.        ,  0.98774096,  0.        ,
         0.        ],
       [ 0.23165931,  0.        ,  2.23047909,  0.        ,  0.        ,
         0.54058861],
       [ 1.50554324,  0.54163424,  0.14517687,  0.        ,  0.        ,
         0.41554909]])