# 此样例是二分类问题，建立带有一个包含四个神经元的隐藏层的神经网络
## 输入
x1, x2
## 输出
y = x1 + x2 >= 0? 1: 0;
## 实现方法
使用优化器实现梯度下降，如Adam、RMSProp等

In [1]:
import torch

## 产生数据
使用`torch.randn()`随机生成满足标准正态分布的张量，size为$1000\times2$。

In [2]:
x = torch.randn(1000, 2)
x

tensor([[ 0.0745,  1.2528],
        [ 1.5784,  1.0894],
        [-1.5294, -0.2706],
        ...,
        [-1.8367, -0.4637],
        [-0.6858,  1.0578],
        [-0.9760,  0.5418]])

使用`torch.sum(input, dim, keepdim=False, dtype=None)`生成label，其参数如下：
* `input`：需要求和的tensor
* `dim`：需要求和的维度
* `keepdim`：默认为False，如果为True则求和后的输出的维数与input相同

也可以使用`y[x.sum(dim=1) >= 0] = 1`生成label。

In [3]:
y = torch.zeros(1000, 1)
y[torch.sum(x, dim=1) >= 0] = 1
# y[x.sum(dim=1) >= 0] = 1
y

tensor([[1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
      

## 建立模型并训练（	使用`torch.nn.optim`进行梯度下降）
### 建立网络
使用`torch.nn.Sequential()`建立模型

In [4]:
model = torch.nn.Sequential(
            torch.nn.Linear(2, 4),
            torch.nn.ReLU(),
            torch.nn.Linear(4, 1),
            torch.nn.Sigmoid()
        )

### 损失函数
损失函数使用`torch.nn.BCELoss()`，即Binary Cross Entrophy Loss，适用于使用Sigmoid激活函数的二分类问题。
* `input`: Tensor of arbitrary shape
* `target`: Tensor of the same shape as input

### 优化器
使用`torch.optim.Adam()`进行梯度下降，其重要的参数为：
* `params`：网络的权重，通过`model.parameters()`获取，为可迭代类型
* `lr`：学习率learning_rate，默认为1e-3

### 自动求导
* `optimizer.zero_grad()`：在反向传播之前，使用optimizer将它要更新的所有张量的梯度清零(这些张量是模型可学习的权重)
* `loss.backward()`：反向传播：根据模型的参数计算loss的梯度
* `optimizer.step()`：调用Optimizer的step函数使它所有参数更新

也可将以上三条语句替换为以下代码：
```python
# 反向传播之前清零梯度
model.zero_grad()
loss.backward()
# 使用梯度下降更新权重。
# 每个参数都是张量，所以我们可以像我们以前那样可以得到它的数值和梯度
with torch.no_grad():
    for param in model.parameters():
        param -= learning_rate * param.grad
```
此时不使用优化器，而是在`torch.no_grad()`上下文环境中更新梯度。

In [5]:
learning_rate = 1e-3
loss_fn = torch.nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for t in range(1000):
    y_pred = model(x)
    loss = loss_fn(y_pred, y)
    print(t, loss.item())
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 0.6379839181900024
1 0.6372369527816772
2 0.6364894509315491
3 0.6357426047325134
4 0.6349954009056091
5 0.6342477202415466
6 0.6335005760192871
7 0.6327520608901978
8 0.6320033073425293
9 0.6312547326087952
10 0.6305060982704163
11 0.6297574043273926
12 0.629008948802948
13 0.6282597184181213
14 0.6275110244750977
15 0.6267624497413635
16 0.6260126829147339
17 0.6252627968788147
18 0.6245136857032776
19 0.6237636208534241
20 0.623012900352478
21 0.6222620010375977
22 0.6215111613273621
23 0.6207584142684937
24 0.620006263256073
25 0.6192534565925598
26 0.6185005903244019
27 0.6177473068237305
28 0.6169934272766113
29 0.6162385940551758
30 0.615482747554779
31 0.6147268414497375
32 0.6139704585075378
33 0.613213300704956
34 0.6124555468559265
35 0.611697793006897
36 0.6109392642974854
37 0.6101805567741394
38 0.6094213724136353
39 0.6086622476577759
40 0.6079013347625732
41 0.6071389317512512
42 0.6063774824142456
43 0.6056143045425415
44 0.6048504114151001
45 0.6040849089622498
46 0

371 0.32560214400291443
372 0.3248246908187866
373 0.32404887676239014
374 0.3232749402523041
375 0.3225025534629822
376 0.3217318654060364
377 0.3209628462791443
378 0.32019519805908203
379 0.31942954659461975
380 0.31866443157196045
381 0.3179011940956116
382 0.3171391189098358
383 0.31637927889823914
384 0.31562140583992004
385 0.31486502289772034
386 0.31411001086235046
387 0.3133571147918701
388 0.31260621547698975
389 0.3118576407432556
390 0.31111106276512146
391 0.31036561727523804
392 0.3096224069595337
393 0.3088805079460144
394 0.30814120173454285
395 0.30740371346473694
396 0.3066682517528534
397 0.3059346079826355
398 0.3052031993865967
399 0.3044736087322235
400 0.30374670028686523
401 0.30302149057388306
402 0.3022984266281128
403 0.3015766441822052
404 0.3008562922477722
405 0.3001369535923004
406 0.2994193732738495
407 0.29870346188545227
408 0.2979894280433655
409 0.2972767949104309
410 0.2965659201145172
411 0.29585427045822144
412 0.295144259929657
413 0.29443565011

812 0.13952989876270294
813 0.1393461972475052
814 0.1391633003950119
815 0.13898099958896637
816 0.13879917562007904
817 0.13861794769763947
818 0.1384371668100357
819 0.1382569819688797
820 0.13807716965675354
821 0.13789808750152588
822 0.13771964609622955
823 0.13754166662693024
824 0.13736417889595032
825 0.1371871381998062
826 0.13701067864894867
827 0.13683472573757172
828 0.13665929436683655
829 0.13648416101932526
830 0.13630981743335724
831 0.13613566756248474
832 0.1359621286392212
833 0.13578914105892181
834 0.13561640679836273
835 0.13544447720050812
836 0.13527265191078186
837 0.13510142266750336
838 0.13493075966835022
839 0.13476046919822693
840 0.134590744972229
841 0.13442133367061615
842 0.13425254821777344
843 0.13408417999744415
844 0.13391616940498352
845 0.13374879956245422
846 0.13358189165592194
847 0.13341543078422546
848 0.13324935734272003
849 0.13308387994766235
850 0.1329185962677002
851 0.13275398313999176
852 0.13258971273899078
853 0.13242597877979279
8

## 创建测试样例并进行测试

In [6]:
x_test = torch.randn(100, 2)
x_test

tensor([[ 0.6483, -1.7291],
        [-0.8005,  0.1327],
        [-0.9405, -1.1010],
        [-0.7488, -1.1779],
        [-2.0758, -0.3546],
        [-1.8351,  1.1915],
        [-1.1949, -0.2665],
        [-0.1990, -0.1263],
        [ 0.5126,  0.6300],
        [-0.3034,  1.6364],
        [-1.3917,  0.2670],
        [-1.5884, -3.0683],
        [ 0.2465,  0.5223],
        [-1.1889, -0.7998],
        [ 1.1082,  0.1497],
        [ 0.7781, -0.1030],
        [-0.3398,  0.5734],
        [-0.3579, -1.9046],
        [-0.7103,  1.5194],
        [ 1.1019, -0.3515],
        [ 1.7460, -1.1121],
        [-0.1986, -0.9290],
        [-0.2504,  0.0566],
        [-1.0126,  0.2362],
        [ 0.5543,  0.5620],
        [-1.2862,  0.2296],
        [ 0.2894,  0.3309],
        [ 1.4080, -0.3574],
        [-0.3311, -1.8519],
        [ 0.9288, -1.0814],
        [-0.6169, -0.0170],
        [-0.8562,  2.5685],
        [-0.1703, -0.9603],
        [ 0.9163, -1.4430],
        [-1.1216,  1.6422],
        [-1.3011,  1

In [7]:
y_test = torch.zeros(100, 1)
y_test[torch.sum(x_test, dim=1) >= 0] = 1
# y_test[x_test.sum(dim=1) >= 0] = 1
y_test

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
      

In [8]:
y_test_pred = torch.zeros(100, 1)
y_test_pred[model(x_test) >= .5] = 1
y_test_pred

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
      

In [9]:
result = torch.zeros(100, 1)
result[y_test == y_test_pred] = 1
print('accurate: {}'.format(result.sum().item() / 100))

accurate: 1.0
